site_name: TEC4
site_url: https://MdSmateriales.github.io/TEC4/

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.indexes
    - search.suggest
    - search.highlight
    - navigation.sections

nav:
  - Inicio: index.md
  - Unidad 1. Proceso Tecnológico:
      - Fases: unidad-1/metodologia-proyectos.md
      - Ejercicio de planificación: unidad-1/ej1.md
      - Herramientas para la gestión de proyectos: unidad-1/herramientas-proyectos.md
      - Metodologías de planificación de proyectos: unidad-1/planificacion-proyectos.md
  - Unidad 2. Electrónica analógica:
      - Componentes y Ley de Ohm: unidad-2/analogica.md
      - Esquemas y Circuitos: unidad-2/simulacion.md
  - Unidad 3. Electrónica digital:
      - Algebra de Boole: unidad-3/boole.md
      - Entornos de Programación: unidad-3/digital.md
  - Unidad 4. Automatización:
      - Pines y Control Digital: unidad-4/pines-digitales.md
      - Actuadores Básicos: unidad-4/actuadores-basicos.md
      - Lectura de Sensores: unidad-4/sensores.md
      - Motores y Control: unidad-4/motores.md
  - Unidad 5. Pensamiento computacional:
      - Algoritmos y Estructuras: unidad-5/algoritmos.md
      - Tecnologías emergentes: unidad-5/entornos.md
  - Unidad 6. Tecnología sostenible, Diseño y Fabricación:
      - Arquitectura bioclimática: unidad-6/arquitecturas.md
      - Clasificación de Materiales: unidad-6/materiales.md
      - Impresión 3D y Taller: unidad-6/fabricacion.md
  - Unidad 7. Servicios sostenibles:
      - Servicios sostenibles: unidad-7/servicios.md
  - Unidad 8. Neumática e hidráulica:
      - Neumática: unidad-8/neumatica.md
      - Proyecto de neumática: unidad-8/proyecto.md
