site_name: TEC4
site_url: https://MdSmateriales.github.io/TEC4/

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.indexes
    - search.suggest
    - search.highlight
    - navigation.sections

nav:
  - Inicio: index.md
  - Unidad 1. Pensamiento computacional:
      - Algoritmos y Estructuras: unidad-1/algoritmos.md
      - Tecnologías emergentes: unidad-1/entornos.md
  - Unidad 2. Proceso Tecnológico:
      - Metodología y Fases: unidad-2/metodologia.md
      - Memoria Técnica: unidad-2/memoria.md
  - Unidad 3. Electrónica analógica:
      - Componentes y Ley de Ohm: unidad-3/analogica.md
      - Esquemas y Circuitos: unidad-3/simulacion.md
  - Unidad 4. Electrónica digital:
      - Algoritmos y Estructuras: unidad-4/boole.md
      - Entornos de Programación: unidad-4/digital.md
  - Unidad 5. Automatización:
      - Pines y Control Digital: unidad-5/pines-digitales.md
      - Actuadores Básicos: unidad-5/actuadores-basicos.md
      - Lectura de Sensores: unidad-5/sensores.md
      - Motores y Control: unidad-5/motores.md
  - Unidad 6. Tecnología sostenible, Diseño y Fabricación:
      - Arquitectura bioclimática: unidad-6/arquitecturas.md
      Clasificación de Materiales: unidad-6/materiales.md
      - Impresión 3D y Taller: unidad-6/fabricacion.md
  - Unidad 7. Servicios sostenibles:
      - Servicios sostenibles: unidad-7/servicios.md
  - Unidad 8. Neumática e hidráulica:
      - Neumática: unidad-8/neumatica.md
      - Proyecto de neumática: unidad-8/proyecto.md
